### ISSUE TITLE
Failed to activate the title-case package

### ISSUE THREAD

**Issue by kurtschlatzer** [max/atom-title-case#1] opened 2015-04-28 14:37 UTC
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.194.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [title-case](https://github.com/max/atom-title-case) package, v0.2.0
### Stack Trace

Failed to activate the title-case package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (/Users/kurtschlatzer/.atom/packages/title-case/lib/title-case.coffee:4:32)
    at Package.module.exports.Package.activateNow (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:222:19)
    at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:203:30
    at Package.module.exports.Package.measure (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:147:15)
    at Package.module.exports.Package.activate (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:195:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package-manager.js:434:21)
    at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package-manager.js:418:29
    at Config.module.exports.Config.transact (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package-manager.js:413:19)
    at PackageManager.module.exports.PackageManager.activate (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package-manager.js:394:46)
    at Atom.module.exports.Atom.startEditorWindow (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/atom.js:623:21)
    at Object.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:12:8)
    at Object.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:23:4)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
    at Module.load (module.js:347:32)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "base16-spacegray-syntax"
    ],
    "excludeVcsIgnoredPaths": false,
    "followSymlinks": true,
    "disabledPackages": [
      "autosave",
      "autoflow",
      "background-tips",
      "autocomplete",
      "welcome",
      "language-c",
      "language-clojure",
      "language-csharp",
      "language-go",
      "language-java",
      "language-objective-c",
      "language-perl",
      "language-python",
      "language-toml",
      "metrics",
      "open-on-github",
      "pepper-autocomplete",
      "autocomplete-paths",
      "dash",
      "file-templates",
      "git-log",
      "linter-doiuse",
      "package-list",
      "wordpress-api",
      "timecop",
      "bookmarks",
      "styleguide",
      "feedback",
      "spell-check",
      "wrap-guide",
      "Remote-FTP",
      "autoclose-html",
      "cut-line",
      "lorem-ipsum",
      "w3c-validation",
      "esformatter",
      "linter-tidy",
      "linter-phpcs",
      "linter-csslint",
      "linter-htmlhint",
      "less-autocompile",
      "language-mustache"
    ],
    "projectHome": "/Users/kurtschlatzer/Projects"
  }
}
```
### Installed Packages

``` coffee
# User
Package-Upgrader, v0.3.1
autocomplete-plus, v2.12.0
base16-spacegray-syntax, v0.2.0
editorconfig, v1.0.0
git-history, v2.5.0
indent-guide-improved, v1.1.1
language-generic-config, v0.1.4
language-htaccess, v0.1.1
language-svg, v0.8.0
linter, v0.12.1
linter-jshint, v0.1.2
linter-less, v0.3.1
linter-php, v0.0.12
linter-scss-lint, v0.0.14
open-last-project, v0.4.1
pane-layout-plus, v0.6.7
pretty-json, v0.3.3
sassbeautify, v0.2.0
simple-drag-drop-text, v0.2.2
synced-sidebar, v0.2.3
text-manipulation, v0.6.0
title-case, v0.2.0

# Dev
No dev packages
```

**Comment by UnreachableCode** [comment] 2015-07-06 12:50
Has this been fixed yet? I just tried a single and a multiple selection and the command would just hang both times.

**Comment by alexgleason** [comment] 2015-07-06 15:31
@UnreachableCode I created a pull request to fix this, just waiting for it to be reviewed and merged.

In the meantime, feel free to use my fork of this project where the issue is fixed. It can be found here: https://github.com/alexgleason/atom-title-case

Just clone it into your ~/.atom/packages directory.

**Comment by UnreachableCode** [comment] 2015-07-07 08:57
Hey,

Thanks very much Alex. Very helpful.

-Charlie.

**Closed as completed** 2015-07-08 04:00 UTC
